Initial support for thumbnails for existing files.
OpenRefine/CommonsExtension pull request #88
Opened 2022-12-02 15:12 UTC by wetneb

Closes #58.

This changes requires to run OpenRefine from the `wetneb:5154-extension-point-for-cell-rendering` branch (which corresponds to the PR https://github.com/OpenRefine/OpenRefine/pull/5312).
The aim is that this PR is merged before 3.7, so that the extension can rely on it to implement the thumbnails.

Changes to the thumbnails themselves can then be made independently of OpenRefine's release cycle.

Since this PR is only about existing files, I did not add an explicit toggle to turn thumbnails on and off - they are just enabled by default for all cells that are reconciled to a media file on a Wikibase instance.

One thing I would probably still add is a waiting spinner when the full screen image is being loaded. It would also be worth checking the thumbnails are requested in a way that maximizes the chances of cache hits (which I am not sure I got right so far).

2022-12-06 19:40 UTC, trnstlntk commented
I tested it on a variety of files, and it works excellently. It indeed has that wow factor! I get thumbnails for images, videos and PDFs. In some cases (I saw it with a PDF and a video) the pop-up loads slowly indeed (is that due to file size?) and a spinner would indeed make sense to indicate that something is happening.

The size of the thumbnails is great IMO. Maybe other users will have different opinions but I think it's a good size to be able to discern files well without overwhelming.

I can imagine that a toggle function will be useful to add later, but this is absolutely great for now.

2022-12-06 19:42 UTC, trnstlntk commented on module/scripts/project/thumbnail-renderer.js
> +   320, 640, 800, 1024, 1280, 1920, 2560, 2880
Interesting, makes sense. Which one did you use now, 640?

2022-12-06 19:43 UTC, trnstlntk approved these changes

2022-12-06 21:49 UTC, lozanaross approved these changes

2023-02-28 07:54 UTC, trnstlntk commented
@wetneb I noticed that this PR hasn't been merged "back in the days" (I can't recall why?) - but thumbnails do work in the Commons extension, except for this little annoying bug here: #89 

Can you recall why this would still be open?

Thanks for digging into your memory :-)

2023-02-28 08:00 UTC, trnstlntk commented
> @wetneb I noticed that this PR hasn't been merged "back in the days" (I can't recall why?) - but thumbnails do work in the Commons extension, except for this little annoying bug here: #89
> 
> Can you recall why this would still be open?
> 
> Thanks for digging into your memory :-)

If you prefer not to dig into this anymore (which is fine), I'll take the freedom to close this PR as not done, to reduce confusion.

2023-02-28 08:34 UTC, wetneb commented
I think you do need to merge this PR - I do not think thumbnail support works without it. Could it be that the version of the Commons extension you are using is generated from this PR?

So I would recommend merging this and releasing a new version of the extension.

2023-02-28 08:55 UTC, trnstlntk commented
> I think you do need to merge this PR - I do not think thumbnail support works without it. Could it be that the version of the Commons extension you are using is generated from this PR?
> 
> So I would recommend merging this and releasing a new version of the extension.

Thanks, you're entirely correct! I now feel very stupid 🙈 - I was indeed working from this PR myself.

I notice we released 0.1.0 without thumbnail support (it was also not included in the release notes). I prefer for someone to continue adjusting this existing PR to fix the #89 bug, and also someone else to release the new version. I did the previous release myself but found it very difficult, I had absolutely no idea what I was doing except for following instructions blindly. IMO it's a job for someone with stronger technical skills and familiarity with Git/GitHub processes.

I'll see how I can adjust the bounty to include these requirements.

2023-02-28 09:02 UTC, trnstlntk requested changes
After quite a bit more testing of this PR, I have noticed that it doesn't support all file extensions on Wikimedia Commons, see issue #89 (capitalized file names)

I suggest to update this PR accordingly, then merge, and do a new release of the extension.

2023-03-08 11:59 UTC, merged

2024-02-15 01:43 UTC, vitaly-zdanevich commented
But I have previews only on mouse hover:
![image](https://github.com/OpenRefine/CommonsExtension/assets/3514015/e637a862-0cf7-4542-887d-8f4c186c7280)